// components/ui/ProjectCard.tsx
export default async function ProjectCard({
  title,
  techStack,
  description,
  links,
}: {
  title: string;
  techStack: string[];
  description: string;
  links: { name: string; url: string }[];
}) {
  return (
    <div className="border p-6 rounded-md bg-eggshell max-w-[280px] transform transition-all duration-200 hover:-translate-y-2">
      <p className="text-eerie-black font-bagnard text-xl leading-none mb-2">
        {title}
      </p>
      <ul className="flex gap-2 mb-4 flex-wrap gap-y-1">
        {techStack.map((tech, index) => (
          <li
            className="bg-reseda-green px-2 rounded-sm text-[12px]"
            key={index}
          >
            {tech}
          </li>
        ))}
      </ul>
      <p className="mb-4 text-eerie-black text-[14px]">{description}</p>
      <ul className="flex gap-3 text-[13px] underline underline-offset-4 text-eerie-black decoration-reseda-green opacity-90">
        {links.map((link, index) => (
          <li key={index}>
            <a href={link.url} target="_blank" rel="noopener noreferrer">
              {link.name}
            </a>
          </li>
        ))}
      </ul>
    </div>
  );
}

// components/ProjectCard.vue
<template>
  <div
    class="bg-[#EEEAD7] shadow-sm rounded-lg w-full max-w-3xl mb-6 flex flex-col justify-between transition-transform duration-200 ease-in-out hover:-translate-y-1"
  >
    <div class="p-6 flex flex-col">
      <h3 class="text-xl font-bold text-persian mb-2">{{ title }}</h3>
      <p class="text-sm mb-1">{{ description }}</p>
    </div>
    <div>
      <div class="flex flex-wrap gap-1 mb-4 px-6">
        <BadgeTechnology
          calss
          v-for="(tech, index) in technologies"
          :key="index"
        >
          {{ tech }}
        </BadgeTechnology>
      </div>
      <div
        class="flex flex-wrap gap-4 mt-2 bg-[#FFDFA0] px-6 py-4 rounded-b-lg"
      >
        <a
          v-if="github"
          :href="github"
          class="text-ocean font-bold hover:underline"
          target="_blank"
          rel="noopener noreferrer"
        >
          GitHub →
        </a>
        <a
          v-if="live"
          :href="live"
          class="text-ocean font-bold hover:underline"
          target="_blank"
          rel="noopener noreferrer"
        >
          Live →
        </a>
      </div>
    </div>
  </div>
</template>

<script setup>
import BadgeTechnology from "./ui/BadgeTechnology.vue";

defineProps({
  title: String,
  description: String,
  technologies: Array,
  github: String,
  live: String,
});
</script>
